[package]
name = "perple"
version = "0.1.0"
edition = "2024"

[dependencies]
ort = "=2.0.0-rc.10"
image = { version = "0.*" }
ndarray = { version = "0.*", features = ["rayon"] }
raqote = "0.*"
pcd-rs = "0.*"
nalgebra = {version = "0.*", features = ["std"]}
bevy = {version = "0.*"}
toml = "0.*"
serde = { version = "1.*", features = ["derive"] }
