name = "GPF 地面检测"
type = "gpf"
preprocessor = "passthrough"

[quick]
frames = 1
params = [
  { n_lpr = 100, th_seed = 0.5, th_dist = 0.2 },
  { n_lpr = 100, th_seed = 0.5, th_dist = 0.3 },
  { n_lpr = 200, th_seed = 0.5, th_dist = 0.2 },
  { n_lpr = 200, th_seed = 0.5, th_dist = 0.3 },
]

[full]
frames = 10
params = [
  { n_lpr = 50, th_seed = 0.3, th_dist = 0.15 },
  { n_lpr = 50, th_seed = 0.5, th_dist = 0.30 },
  { n_lpr = 50, th_seed = 0.7, th_dist = 0.50 },
  { n_lpr = 100, th_seed = 0.3, th_dist = 0.30 },
  { n_lpr = 100, th_seed = 0.5, th_dist = 0.50 },
  { n_lpr = 100, th_seed = 0.7, th_dist = 0.15 },
  { n_lpr = 200, th_seed = 0.3, th_dist = 0.20 },
  { n_lpr = 200, th_seed = 0.5, th_dist = 0.30 },
  { n_lpr = 200, th_seed = 0.7, th_dist = 0.15 },
  { n_lpr = 300, th_seed = 0.3, th_dist = 0.50 },
  { n_lpr = 300, th_seed = 0.5, th_dist = 0.15 },
  { n_lpr = 300, th_seed = 0.7, th_dist = 0.30 },
]

[stats]
fastest_ms = 7.1244000000000005
slowest_ms = 32.994299999999996
avg_ms = 12.701852500000001
median_ms = 8.11275
last_run = "1778747722"
