name = "直方图扩展地面检测"
type = "histogram"
preprocessor = "passthrough"

[quick]
frames = 1
params = [
  { expand = 0.10 },
]

[full]
frames = 10
params = [
  { expand = 0.05 },
  { expand = 0.10 },
  { expand = 0.15 },
  { expand = 0.20 },
]

[stats]
fastest_ms = 5.4422999999999995
slowest_ms = 8.289100000000001
avg_ms = 5.98058
median_ms = 5.9012
last_run = "1778747722"
