name = "直方图扩展地面检测"
type = "histogram"
preprocessor = "passthrough"

[quick]
frames = 1
params = [
  { expand = 0.10 },
]

[full]
frames = 10
params = [
  { expand = 0.05 },
  { expand = 0.10 },
  { expand = 0.15 },
  { expand = 0.20 },
]

[stats]
fastest_ms = 5.6057
slowest_ms = 7.6715
avg_ms = 6.264795000000001
median_ms = 6.025449999999999
last_run = "1778476868"
