name = "RANSAC 地面拟合"
type = "ransac"
preprocessor = "passthrough"

[quick]
frames = 1
params = [
  { distance = 0.2, iterations = 50 },
  { distance = 0.2, iterations = 100 },
  { distance = 0.4, iterations = 50 },
  { distance = 0.4, iterations = 100 },
]

[full]
frames = 10
params = [
  { distance = 0.1, iterations = 50 },
  { distance = 0.1, iterations = 100 },
  { distance = 0.1, iterations = 200 },
  { distance = 0.2, iterations = 50 },
  { distance = 0.2, iterations = 100 },
  { distance = 0.2, iterations = 200 },
  { distance = 0.4, iterations = 50 },
  { distance = 0.4, iterations = 100 },
  { distance = 0.4, iterations = 200 },
  { distance = 0.6, iterations = 50 },
  { distance = 0.6, iterations = 100 },
  { distance = 0.6, iterations = 200 },
]

[stats]
fastest_ms = 11.8893
slowest_ms = 60.9977
avg_ms = 32.000733333333336
median_ms = 26.9336
last_run = "1778476868"
