name = "网格 DBSCAN 聚类"
type = "dbscan_grid"
preprocessor = "ground+wall"

[quick]
frames = 1
params = [
  { eps = 0.20, min_pts = 3 },
  { eps = 0.20, min_pts = 5 },
  { eps = 0.30, min_pts = 3 },
  { eps = 0.30, min_pts = 5 },
  { eps = 0.50, min_pts = 3 },
  { eps = 0.50, min_pts = 5 },
]

[full]
frames = 10
params = [
  { eps = 0.15, min_pts = 3 },
  { eps = 0.15, min_pts = 10 },
  { eps = 0.20, min_pts = 5 },
  { eps = 0.25, min_pts = 3 },
  { eps = 0.30, min_pts = 10 },
  { eps = 0.40, min_pts = 5 },
  { eps = 0.50, min_pts = 3 },
  { eps = 0.60, min_pts = 10 },
  { eps = 0.80, min_pts = 5 },
]
[stats]
fastest_ms = 4.6316999999999995
slowest_ms = 862.0156
avg_ms = 152.39140666666668
median_ms = 15.125499999999999
last_run = "1778672779"
