name = "半径离群点剔除"
type = "radius_outlier"
preprocessor = "ground+wall"

[quick]
frames = 1
params = [
  { radius = 0.20, min_pts = 3 },
  { radius = 0.30, min_pts = 3 },
  { radius = 0.20, min_pts = 5 },
]

[full]
frames = 10
params = [
  { radius = 0.15, min_pts = 3 },
  { radius = 0.15, min_pts = 5 },
  { radius = 0.20, min_pts = 3 },
  { radius = 0.20, min_pts = 5 },
  { radius = 0.25, min_pts = 3 },
  { radius = 0.25, min_pts = 5 },
  { radius = 0.30, min_pts = 3 },
  { radius = 0.30, min_pts = 5 },
  { radius = 0.40, min_pts = 3 },
]
[stats]
fastest_ms = 4.3873999999999995
slowest_ms = 457.336
avg_ms = 88.61868888888893
median_ms = 9.23005
last_run = "1778738500"
