name = "半径离群点剔除"
type = "radius_outlier"
preprocessor = "ground+wall"

[quick]
frames = 1
params = [
  { radius = 0.20, min_pts = 3 },
  { radius = 0.30, min_pts = 3 },
  { radius = 0.20, min_pts = 5 },
]

[full]
frames = 10
params = [
  { radius = 0.15, min_pts = 3 },
  { radius = 0.15, min_pts = 5 },
  { radius = 0.20, min_pts = 3 },
  { radius = 0.20, min_pts = 5 },
  { radius = 0.25, min_pts = 3 },
  { radius = 0.25, min_pts = 5 },
  { radius = 0.30, min_pts = 3 },
  { radius = 0.30, min_pts = 5 },
  { radius = 0.40, min_pts = 3 },
]
[stats]
fastest_ms = 4.6768
slowest_ms = 556.169
avg_ms = 133.18323444444442
median_ms = 11.189599999999999
last_run = "1778476637"
