name = "半径离群点剔除"
type = "radius_outlier"
preprocessor = "ground+wall"

[quick]
frames = 1
params = [
  { radius = 0.20, min_pts = 3 },
  { radius = 0.30, min_pts = 3 },
  { radius = 0.20, min_pts = 5 },
]

[full]
frames = 10
params = [
  { radius = 0.15, min_pts = 3 },
  { radius = 0.15, min_pts = 5 },
  { radius = 0.20, min_pts = 3 },
  { radius = 0.20, min_pts = 5 },
  { radius = 0.25, min_pts = 3 },
  { radius = 0.25, min_pts = 5 },
  { radius = 0.30, min_pts = 3 },
  { radius = 0.30, min_pts = 5 },
  { radius = 0.40, min_pts = 3 },
]
[stats]
fastest_ms = 3.7986999999999997
slowest_ms = 11.5165
avg_ms = 6.213109999999996
median_ms = 6.1255500000000005
last_run = "1778474406"
