# 统一超参数配置文件
# 合并了训练、优化器和数据增强的所有参数

# 训练参数
epochs: 200
workers: 4
batch: 8
imgsz: 640
save_period: 10
cos_lr: true
patience: 50

# 学习率调度参数
warmup_epochs: 3
warmup_momentum: 0.8
warmup_bias_lr: 0.1
close_mosaic: 10  # 在最后10个epoch关闭mosaic增强

# 优化器参数
optimizer: Adam

Adam: 
  lr0: 0.0003
  lrf: 0.01
  weight_decay: 0.05

SGD:
  lr: 0.01
  momentum: 0.937
  weight_decay: 0.005

AdamW:
  lr0: 0.0003
  lrf: 0.01
  weight_decay: 0.05

# 数据增强参数
augment:
  # HSV色彩空间调整
  hsv_h: 0.015  # 色调调整 (Hue)
  hsv_s: 0.7    # 饱和度调整 (Saturation)
  hsv_v: 0.4    # 明度调整 (Value)
  
  # 几何变换
  degrees: 10.0     # 旋转角度
  translate: 0.2    # 平移比例
  scale: 0.5        # 缩放比例
  shear: 10.0       # 剪切变换
  perspective: 0.001  # 透视变换
  
  # 翻转概率
  flipud: 0.0   # 垂直翻转概率（行人识别任务不推荐使用）
  fliplr: 0.5   # 水平翻转概率
  
  # 其他增强技术
  mosaic: 1.0       # 马赛克增强概率
  mixup: 0.2        # MixUp增强概率
  copy_paste: 0.3   # 复制粘贴增强概率
  erasing: 0.4      # 随机擦除概率